name: Publish TechDocs Site

on:
  push:
    paths:
      - "docs/**"
      - "mkdocs.yml"

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest

    # The following secrets are required in your CI environment for publishing files to AWS S3.
    # e.g. You can use GitHub Organization secrets to set them for all existing and new repositories.
    env:
      TECHDOCS_S3_BUCKET_NAME: ${{'${{secrets.AWS_S3_BUCKET}}'}} 
      AWS_ACCESS_KEY_ID:  ${{'${{secrets.AWS_ACCESS_KEY_ID}}'}} 
      AWS_SECRET_ACCESS_KEY:  ${{'${{secrets.AWS_SECRET_ACCESS_KEY}}'}} 
      AWS_REGION: ${{'${{secrets.AWS_REGION}}'}}
      ENTITY_NAMESPACE: 'default'
      ENTITY_KIND: 'Component'
      ENTITY_NAME: 'my-doc-entity'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type awsS3 --storage-name ${{'${{secrets.AWS_S3_BUCKET}}'}} --entity default/component/backstages